repos:
  - repo: https://github.com
    rev: 24.10.0
    hooks:
      - id: black
        args: [--line-length=100]

  - repo: https://github.com
    rev: v0.14.1
    hooks:
      - id: ruff
        args: [--fix]
