#!/usr/bin/env python3
"""Phase 2: High-Speed Serial Ingestion Daemon.

Monitors physical USB-UART bus streams, insulates the pipeline against
environmental line noise corruption, and parses raw waveform telemetry frames.
"""
import re
import sys
import logging
import numpy as np

logging.basicConfig(level=logging.INFO, format='[%(asctime)s] [%(levelname)s] %(message)s')
logger = logging.getLogger("SerialDaemon")

class VivicSerialDaemon:
    def __init__(self, port: str = "COM3", baud: int = 115200, max_line_bytes: int = 256):
        """Initializes the ingestion daemon with explicit sanity-bounding gates."""
        self.port = port
        self.baud = baud
        self.max_line_bytes = max_line_bytes  # Hard boundary protection against memory floods

        # Telemetry structural health counters
        self.frames_parsed = 0
        self.frames_dropped = 0

        # Strict validation pattern matching our exact firmware footprint with 4 decimals
        self.telemetry_regex = re.compile(
            r"^V1:(?P<v1>-?\d+\.\d{4}),V2:(?P<v2>-?\d+\.\d{4}),V3:(?P<v3>-?\d+\.\d{4}),V4:(?P<v4>-?\d+\.\d{4}),CRC:0x(?P<crc>[0-9A-Fa-f]{2})$"
        )

    @staticmethod
    def compute_binary_crc8(data: bytes) -> int:
        """Computes matching Dallas/Maxim CRC-8 checksum over raw byte sequences."""
        crc = 0x00
        for byte in data:
            crc ^= byte
            for _ in range(8):
                if crc & 0x80:
                    crc = ((crc << 1) ^ 0x31) & 0xFF
                else:
                    crc = (crc << 1) & 0xFF
        return crc

    def process_raw_line(self, raw_line: bytes) -> tuple:
        """Sanitizes, validates, and decodes incoming serial packets with string-level payload CRC checks."""
        try:
            if len(raw_line) > self.max_line_bytes:
                self.frames_dropped += 1
                logger.warning(f"Line bounds breached ({len(raw_line)} bytes). Purging corrupted frame.")
                return "CORRUPTED", None

            clean_str = raw_line.decode('utf-8', errors='replace').strip()
            if not clean_str:
                return "EMPTY", None

            if "FAULT" in clean_str:
                self.frames_dropped += 1
                logger.error("[💥 HARDWARE ALERT] Embedded firmware reporting an active ADC DRDY pin timeout!")
                return "HARDWARE_FAULT", None

            match = self.telemetry_regex.match(clean_str)
            if not match:
                self.frames_dropped += 1
                logger.warning(f"Regex match failure on line: '{clean_str}'. Dropping malformed frame.")
                return "MALFORMED", None

            # Isolate the exact pre-CRC text payload string as generated by the firmware
            payload_str, _ = clean_str.rsplit(",CRC:", 1)
            parts = match.groupdict()
            received_crc = int(parts['crc'], 16)

            # Re-compute CRC-8 over the string bytes of the payload
            if self.compute_binary_crc8(payload_str.encode('utf-8')) != received_crc:
                self.frames_dropped += 1
                logger.warning("String-level CRC verification mismatch! Dropping corrupted transmission data.")
                return "CRC_MISMATCH", None

            extracted_voltages = np.array([float(parts['v1']), float(parts['v2']), float(parts['v3']), float(parts['v4'])], dtype=np.float32)
            self.frames_parsed += 1
            return "SUCCESS", extracted_voltages

        except Exception as err:
            self.frames_dropped += 1
            logger.error(f"Unexpected parsing exception intercepted in ingestion loop: {str(err)}")
            return "PARSE_EXCEPTION", None
